### ISSUE TITLE
Google STT times out at 5 minutes and crashes agent

### ISSUE THREAD

**Issue by nickderobertis** [livekit/agents#1258]
Google STT seems to consistently fail at 5 minutes into the call with the following error:

```
2024-12-18 15:59:58,786 - ERROR livekit.agents.pipeline - Error in _recognize_task
Traceback (most recent call last):
  File "/Users/nick/repos/hellopatient/lk_agent/.venv/lib/python3.12/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nick/repos/hellopatient/lk_agent/.venv/lib/python3.12/site-packages/livekit/agents/pipeline/human_input.py", line 150, in _recognize_task
    await asyncio.gather(*tasks)
  File "/Users/nick/repos/hellopatient/lk_agent/.venv/lib/python3.12/site-packages/livekit/agents/pipeline/human_input.py", line 120, in _audio_stream_co
    stt_stream.push_frame(ev.frame)
  File "/Users/nick/repos/hellopatient/lk_agent/.venv/lib/python3.12/site-packages/livekit/agents/stt/stt.py", line 265, in push_frame
    self._check_not_closed()
  File "/Users/nick/repos/hellopatient/lk_agent/.venv/lib/python3.12/site-packages/livekit/agents/stt/stt.py", line 327, in _check_not_closed
    raise RuntimeError(f"{cls.__module__}.{cls.__name__} is closed")
RuntimeError: livekit.plugins.google.stt.SpeechStream is closed {"pid": 54793, "job_id": "AJ_zKEGnh4r4ttx"}
``` 

Unfortunately it's an unhandled error and so even though we were using it with in the `FallbackAdapter` our agent stops responding completely at 5 minutes into the call. 

I have worked with the Google API before and I know it [times out the streaming connection at 5 minutes](https://cloud.google.com/speech-to-text/v2/quotas#streaming_requests) so I imagine that is the issue. There's [an official tutorial on endless streaming](https://cloud.google.com/speech-to-text/docs/transcribe-streaming-audio#endless-streaming) that shows how to switch to a new request and stitch them together in real-time.

**Comment by potate4** [comment]
same issue.
![image](https://github.com/user-attachments/assets/992d776e-b5c9-4cc9-a13d-48ec36627256)

**Comment by davidzhao** [comment]
fixed in #1291, we'll get a build released later today

**Comment by sorokinvj** [comment]
Using latest version 0.9.0 but still getting stream closure after 5 minutes:
```
Requirement already satisfied: livekit-plugins-google>=0.8.1 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.9.0)
```

```
INFO:voice-assistant: Session time: 286s (4.8min)
ERROR:livekit.agents.pipeline:Error in recognize_task
Traceback (most recent call last):
File "/Users/vladislavsorokin/Projects/joblander/ai-voice-agent-python/venv/lib/python3.9/site-packages/livekit/agents/utils/log.py", line 16, in async_fn_logs
return await fn(args, kwargs)
File "/Users/vladislavsorokin/Projects/joblander/ai-voice-agent-python/venv/lib/python3.9/site-packages/livekit/agents/pipeline/human_input.py", line 150, in recognize_task
await asyncio.gather(tasks)
File "/Users/vladislavsorokin/Projects/joblander/ai-voice-agent-python/venv/lib/python3.9/site-packages/livekit/agents/pipeline/human_input.py", line 120, in audio_stream_co
stt_stream.push_frame(ev.frame)
File "/Users/vladislavsorokin/Projects/joblander/ai-voice-agent-python/venv/lib/python3.9/site-packages/livekit/agents/stt/stt.py", line 265, in push_frame
self.check_not_closed()
File "/Users/vladislavsorokin/Projects/joblander/ai-voice-agent-python/venv/lib/python3.9/site-packages/livekit/agents/stt/stt.py", line 327, in check_not_closed
raise RuntimeError(f"{cls.module}.{cls.name} is closed")
RuntimeError: livekit.plugins.google.stt.SpeechStream is closed {"pid": 92839, "job_id": "AJ_xdeXmeVVsFC8"}
INFO:voice-assistant: Session time: 301s (5.0min)
```

**Comment by davidzhao** [comment]
reopened.. investigating

**Comment by davidzhao** [comment]
the agent runs multiple tasks in order to orchestrate the workflow. we have internal retries for all of the service calls so that API failures could be handled seamlessly. (for example, you probably don't want a single inference timing out to reset the entire state of the agent).

**Comment by davidzhao** [comment]
in this case, the exception wasn't propagated correctly to the retry stack. I've addressed that root cause in the above PR

**Comment by anishhguptaa** [comment]
Hey, I am still getting this issue. Is the fix pushed in the latest version of 1.x or in the 0.12 as well?

`RuntimeError: livekit.plugins.google.stt.SpeechStream is closed`
