### ISSUE TITLE
protobuf and types-protobuf dependencies in Python are inconsistent

### ISSUE THREAD

**Issue by ddeville** [livekit/agents#1353]
The `setup.py` has the following dependency bounds:
```
"protobuf>=3",
"types-protobuf>=4,<5",
```
which were introduced in https://github.com/livekit/agents/pull/198.

What version(s) of protobuf does the library actually support? I'd like to use this package in a project that requires `protobuf>=5` which it looks like `library-agents` should support, but the `type-protobuf<5` upper-bound is too restrictive.

**Comment by flyoozes** [comment]
Any resolution to this? Also facing it as I need my agent to send data via gRPC

**Comment by davidzhao** [comment]
this has been fixed a few versions back

**Comment by flyoozes** [comment]
@davidzhao  was it actually fixed?
https://github.com/livekit/agents/blame/fdc7d19e05949c5a1e9299f10a17d71140dfde6d/livekit-agents/pyproject.toml#L36
I still cannot easily make my agent communicate either gRPC or ConnectRPC because of this constraint... 

I assume I can easily override it without impacting the runtime?

**Comment by davidzhao** [comment]
yeah, sorry about that. we fixed it in the python-sdk package but not agents itself. it's addressed in #3247
