### ISSUE TITLE
Last Agent Message is not Logged During TTS Phase When User Leaves Room in LiveKit Session

### ISSUE THREAD

**Issue by gulamsarvar-bluebash** [livekit/agents#2377]
In our LiveKit-based application, we've observed that when an agent sends a message during the Text-to-Speech (TTS) phase and the user leaves the room—resulting in the room closing—the agent's last message isn't saved in the logs. This behavior leads to incomplete audit trails and potential gaps in conversation history.

Expected Behavior:
Even if the user exits the room and it subsequently closes, the agent's final message during the TTS phase should be captured and saved in the logs to maintain a complete conversation history.

**Comment by longcw** [comment]
This should be fixed in https://github.com/livekit/agents/pull/2309, can you try the latest version 1.0.22

**Comment by gulamsarvar-bluebash** [comment]
Hi, I am already keep room for 20 seconds but still not able to save the transcript
here is my code sample

` 
@ctx.room.on("participant_disconnected")
        def on_participant_disconnected(rparticipant: rtc.RemoteParticipant):
            async def delayed():
                if rparticipant.identity==ParticipantAttributes.participant_identity:
                    if AgentIdentity.live_operator_status in ["active", "ringing"]:
                        await AgentIdentity.remove_participant_from_room(AgentIdentity.live_operator_identity)
                        AgentIdentity.live_operator_status = ""
                        logger.error(f"shutting down session due to participant left the room with operator: {rparticipant}")
                        reason = f"shutting down session due to participant left the room."
                        await asyncio.sleep(20)
                        ctx.shutdown(reason=reason)
                    else:
                        logger.error(f"shutting down session due to participant left the room without operator: {rparticipant}")
                        reason = f"shutting down session due to participant left the room."
                        await asyncio.sleep(20)
                        ctx.shutdown(reason=reason)
`


my shutdown callback code

`
async def my_shutdown_hook():
            logger.info("Shuting down job...")
            start_time = time.time()
            if enable_call_recording:
                try:
                    await AgentEgress.stop_egress_recording(egress_id)
                    elapsed_time = time.time() - start_time
                    logger.warning(f"[voice_agent] Time taken to initialization egress: {elapsed_time}")
                    logger.warning(f"Recording is stoped for egress_id: {egress_id}")
                except Exception as e:
                    logger.critical(f"egress id not found for recording : {recording_sid}, egress_id: {egress_id}")
            await AgentIdentity.delete_room()
            duration = divmod((datetime.now() - datetime.strptime(call_received_at, "%Y-%m-%d %H:%M:%S")).total_seconds(), 60)
            duration = f"{int(duration[0])}:{int(duration[1]):02d}"
            logger.info(f"History {session.history.items}")
            logger.info(f"Current speech {session.current_speech.wait_for_playout}")
            logger.info(f"Conversation history {conversation_history}")
            current_call_transcripts = AgentIdentity.transcript_chat_to_dict(session._chat_ctx.items)
            conversation_transcripts_full = conversation_transcripts + current_call_transcripts
            loop = asyncio.get_running_loop()
`

**Comment by gulamsarvar-bluebash** [comment]
I'm using the latest version, but I'm not receiving the most recent agent transcript. Specifically, I need the transcript that captures the agent's speech right at the moment the room is closed, when the agent is interrupted by the shutdown. That portion of the transcription seems to be missing, and that's what I need to retrieve.

**Comment by longcw** [comment]
for agent transcription, you can just interrupt the agent using `session.interrupt` when participant disconnected?

**Comment by gulamsarvar-bluebash** [comment]
From the `conversation_item_added` event, I only receive the transcript after the agent's playout is completed. However, I need the transcript while the agent is still speaking, specifically when playout is False and the room closes. I'm trying to capture the agent's in-progress speech transcript before it's interrupted.

**Comment by longcw** [comment]
Then you can use a customized [`transcription_node` ](https://docs.livekit.io/agents/build/nodes/#transcription-node) to get the agent transcription while the audio is still playing.

Another options is you interrupt the agent when user disconnected and get that from the `conversation_item_added` event.

**Comment by gulamsarvar-bluebash** [comment]
Hey, I am able to get logs of what the agent is about, to speak, 

```
    async def transcription_node(self, text: AsyncIterable[str], model_settings: ModelSettings) -> AsyncIterable[str]:
        buffer = ""
        async for chunk in text:
            buffer += chunk
            yield chunk
        chat_ctx = self.chat_ctx.copy()
        chat_ctx.add_message(role="assistant", content=buffer)
        global_logger.debug(f"[chat_ctx]: {chat_ctx.to_dict()}")
        await self.update_chat_ctx(chat_ctx)
        global_logger.debug(f"after update chat_ctx {self.chat_ctx.to_dict()}")
        global_logger.debug(f"[Full Agent Transcription]: {buffer}")
```

But I am not getting this agent's transcript. When the session is closed, currently I am using this  `session._chat_ctx.items`
