### ISSUE TITLE
Elevenlabs Turbo v2 High-pitched Voice Regression

### ISSUE THREAD

**Issue by caly-amigo** [livekit/agents#4138]
### Bug Description

`livekit-agents` 1.3.3+ seems to contain a regression where the Elevenlabs Turbo v2 TTS model sounds noticeably high-pitched relative to earlier versions.

I can confirm this regression exists in the following versions:
1. 1.3.3
2. 1.3.5

This seems to suggest that the offending release is 1.3.3.

### Expected Behavior

The Elevenlabs TTS output audio should remain unchanged in pitch.

### Reproduction Steps

```bash
// agent.py 
session = AgentSession(
   tts=elevenlabs.TTS(
       model="eleven_turbo_v2",
       api_key=eleven_api_key,
       voice_id=eleven_voice_id,
   ),
   ...
)
```

### Operating System

N/A

### Models Used

Elevenlabs Turbo v2

### Package Versions

```bash
livekit-agents==1.3.3
```

### Proposed Solution

```python

```

**Comment by longcw** [comment]
it may related to https://github.com/livekit/agents/pull/4098. elevenlabs TTS has a default sample rate 22050, RoomIO output is 24000, when the issue happens it plays 22050 sample rate  at 24khz so it sounds high pitched.

can you check if the issue fixed if you disable the `record` in `session.start(..., record=False)`. If so it's fixed in #4098 and will be included in next release.

**Comment by clovishublin** [comment]
Hey @longcw we have been getting the same issue as soon as we upgraded from 1.2.3 to 1.3.5 to test the observability dashboard. We use Google Chirp 3 HD voices at 48kHz. For us the voices sounded slowed down and low pitched, a common symptom of downsampling (probably to 24/22kHz). I tried your fix to turn off the recording option and it's working normally again.

**Comment by longcw** [comment]
@ClvHbl good to know it's fixed with this. it will be included in next release soon.

**Comment by caly-amigo** [comment]
Thanks @longcw, I can confirm that adding `session.start(record=False)` fixes the issue on 1.3.5.

**Comment by longcw** [comment]
the issue should be fixed in 1.3.6

**Comment by ekaj2** [comment]
@longcw FYI we're still seeing this (just much less severe) on Elevenlabs voices after upgrading to 1.3.6. It does seem to be resolved for Deepgram + Polly.

**Comment by davidzhao** [comment]
@ekaj2 do you have any examples to compare between 1.3.6 vs an older version? i.e. `1.2.3`?
